---

antora:
  name: modules
  dir: www
  modules:
    - name: install
      label: "Install Convert2RHEL"
      solveButton: false
    - name: analyze
      label: "Analyze"
      solveButton: false
    - name: remediate
      label: "Remediate"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty
  - name: "Asciidoc Doc"
    url: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
    external: true
