---
containers: []
virtualmachines:
  - name: "rhel"
    image: "oracle-linux-9-7"
    bootloader: "efi"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
